service: serverless-basic-python-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: test-lambda-jft
    handler: lambda.handler
    description: test-lambda
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"